name: Deploy Front

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Deploy Frontend
        env:
          USER_VM: ${{ secrets.USER_VM }}
          IP_VM: ${{ secrets.IP_VM }}
          VITE_STRIPE_PUBLIC_KEY: ${{ secrets.VITE_STRIPE_PUBLIC_KEY }}
        run: |
          ssh -o StrictHostKeyChecking=no $USER_VM@$IP_VM "
            set -e

            APP_DIR=/var/www/front/ESP-FRONT
            DIST_DIR=/var/www/ESP

            mkdir -p /var/www/front

            if [ -d \"$APP_DIR/.git\" ]; then
              echo 'Repo existant -> update'

              cd $APP_DIR
              git reset --hard
              git clean -fd
              git pull origin main
            else
              echo 'Repo absent -> clone'

              rm -rf $APP_DIR
              git clone https://github.com/ESP-H26-Edgar/ESP-FRONT $APP_DIR
              cd $APP_DIR
            fi

            echo \"VITE_STRIPE_PUBLIC_KEY=$VITE_STRIPE_PUBLIC_KEY\" > .env

            npm ci
            npm run build

            sudo rm -rf $DIST_DIR/*
            sudo cp -r dist/* $DIST_DIR/
          "
